os:
- linux
services: mongodb
language: node_js
node_js:
- stable
before_install:
- git clone https://github.com/ParaffinIoT/apiserver
- cd apiserver
- mv env.sample .env
- npm install
- npm start
- cd ..
install:
- npm install
script:
- npm test
